inference_companion/config/routes.rb
Rails.application.routes.draw do
  resources :sipef_inferences, only: [ :index, :create, :destroy ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

inference_companion/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

inference_companion/app/models/sipef_inference.rb
class SipefInference < ApplicationRecord
  has_one_attached :input_file
  has_one_attached :output_file

  validates :input_file, presence: true

  after_create do
    InferSipefCodesJob.perform_later(id)
  end

  enum :status, { awaiting: 0, processing: 1, processed: 2, failed: 3 }

  def humanize_status
    {
      awaiting: "Aguardando Processamento",
      processing: "Processando",
      processed: "Processado",
      failed: "Processamento Falhou"
    }[status.to_sym]
  end
end

inference_companion/app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :tax_id_number, presence: true, uniqueness: true, length: { maximum: 14 }
  validates :legal_name, presence: true, on: :update, length: { maximum: 150 }
end

inference_companion/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

inference_companion/app/controllers/sipef_inferences_controller.rb
class SipefInferencesController < ApplicationController
  before_action :set_sipef_inference, only: %i[ destroy ]

  # GET /sipef_inferences or /sipef_inferences.json
  def index
    @sipef_inferences = SipefInference.order(created_at: :desc).limit(15)
    @sipef_inference = SipefInference.new
  end

  # POST /sipef_inferences or /sipef_inferences.json
  def create
    @sipef_inference = SipefInference.new(sipef_inference_params)

    respond_to do |format|
      if @sipef_inference.save
        format.html { redirect_to sipef_inferences_path, notice: "Arquivo enviado para processamento." }
        format.json { render json: @sipef_inference, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sipef_inference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sipef_inferences/1 or /sipef_inferences/1.json
  def destroy
    @sipef_inference.destroy!

    respond_to do |format|
      format.html { redirect_to sipef_inferences_path, notice: "Arquivo excluído com sucesso.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sipef_inference
      @sipef_inference = SipefInference.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def sipef_inference_params
      params.expect(sipef_inference: [ :input_file ])
    end
end

inference_companion/app/helpers/application_helper.rb
module ApplicationHelper
end

inference_companion/app/helpers/sipef_inferences_helper.rb
module SipefInferencesHelper
end

inference_companion/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Inference Companion" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Inference Companion">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

inference_companion/app/views/sipef_inferences/_sipef_inference.html.erb
<tr id="<%= dom_id(sipef_inference) %>">
  <td><%= sipef_inference.input_file.filename %></td>
  <td><%= sipef_inference.humanize_status %></td>
  <td>
    <% if %w[processed failed].include?(sipef_inference.status) %>
      <!-- TODO: Implement the download of the output file if the status is processed. -->
      <%= button_to 'Excluir', sipef_inference_path(sipef_inference), method: :delete, data: { confirm: 'Tem certeza?' } %>
    <% end %>
  </td>
</tr>

inference_companion/app/views/sipef_inferences/index.html.erb
<% content_for :title, "Inferências do SIPEF" %>

<h1>Inferências do SIPEF</h1>

<p style="color: green"><%= notice %></p>

<hr>

<%= form_with(model: @sipef_inference, local: true, multipart: true) do |form| %>
  <% if @sipef_inference.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@sipef_inference.errors.count, "error") %> prohibited this sipef_inference from being saved:</h2>
      <ul>
        <% @sipef_inference.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.file_field :input_file, accept: ".xls,.xlsx" %>
    <%= form.submit "Processar Arquivo" %>
  </div>
<% end %>

<hr>

<table id="sipef_inferences">
  <thead>
    <tr>
      <th>Pagamentos para Inferência</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <%= render @sipef_inferences %>
  </tbody>
</table>